import ChargingProfilePurposeType from "./schemas-autogenerated/components/schemas/ChargingProfilePurposeType";
import ChargingRateUnitType from "./schemas-autogenerated/components/schemas/ChargingRateUnitType";
import HTTPValidationError from "./schemas-autogenerated/components/schemas/HTTPValidationError";
import MessageTrigger from "./schemas-autogenerated/components/schemas/MessageTrigger";

import OCPP16CancelReservationProcessorBody from "./schemas-autogenerated/components/schemas/OCPP16CancelReservationProcessorBody";
import OCPP16ChangeAvailabilityProcessorBody from "./schemas-autogenerated/components/schemas/OCPP16ChangeAvailabilityProcessorBody";
import OCPP16ChangeConfigurationAuthenticationProcessorBody from "./schemas-autogenerated/components/schemas/OCPP16ChangeConfigurationAuthenticationProcessorBody";
import OCPP16ChangeConfigurationProcessorBody from "./schemas-autogenerated/components/schemas/OCPP16ChangeConfigurationProcessorBody";
import OCPP16ClearCacheProcessorBody from "./schemas-autogenerated/components/schemas/OCPP16ClearCacheProcessorBody";
import OCPP16ClearChargingProfileProcessorBody from "./schemas-autogenerated/components/schemas/OCPP16ClearChargingProfileProcessorBody";
import OCPP16ExtendedTriggerMessageProcessorBody from "./schemas-autogenerated/components/schemas/OCPP16ExtendedTriggerMessageProcessorBody";
import OCPP16GetCompositeScheduleProcessorBody from "./schemas-autogenerated/components/schemas/OCPP16GetCompositeScheduleProcessorBody";
import OCPP16GetConfigurationAuthenticationProcessorBody from "./schemas-autogenerated/components/schemas/OCPP16GetConfigurationAuthenticationProcessorBody";
import OCPP16GetConfigurationProcessorBody from "./schemas-autogenerated/components/schemas/OCPP16GetConfigurationProcessorBody";
import OCPP16GetDiagnosticsProcessorBody from "./schemas-autogenerated/components/schemas/OCPP16GetDiagnosticsProcessorBody";
import OCPP16GetLocalListVersionProcessorBody from "./schemas-autogenerated/components/schemas/OCPP16GetLocalListVersionProcessorBody";
import OCPP16HeartbeatProcessorBody from "./schemas-autogenerated/components/schemas/OCPP16HeartbeatProcessorBody";
import OCPP16RemoteStartTransactionProcessorBody from "./schemas-autogenerated/components/schemas/OCPP16RemoteStartTransactionProcessorBody";
import OCPP16RemoteStopTransactionProcessorBody from "./schemas-autogenerated/components/schemas/OCPP16RemoteStopTransactionProcessorBody";
import OCPP16ReserveNowProcessorBody from "./schemas-autogenerated/components/schemas/OCPP16ReserveNowProcessorBody";
import OCPP16ResetProcessorBody from "./schemas-autogenerated/components/schemas/OCPP16ResetProcessorBody";
import OCPP16SendDataTransferCertificateInstallationProcessorBody from "./schemas-autogenerated/components/schemas/OCPP16SendDataTransferCertificateInstallationProcessorBody";
import OCPP16SendDataTransferCertificateSignedProcessorBody from "./schemas-autogenerated/components/schemas/OCPP16SendDataTransferCertificateSignedProcessorBody";
import OCPP16SendDataTransferGetCertificateStatusProcessorBody from "./schemas-autogenerated/components/schemas/OCPP16SendDataTransferGetCertificateStatusProcessorBody";
import OCPP16SendDataTransferGetInstalledCertificateIdsProcessorBody from "./schemas-autogenerated/components/schemas/OCPP16SendDataTransferGetInstalledCertificateIdsProcessorBody";
import OCPP16SendDataTransferProcessorBody from "./schemas-autogenerated/components/schemas/OCPP16SendDataTransferProcessorBody";
import OCPP16SendDataTransferTriggerMessageProcessorBody from "./schemas-autogenerated/components/schemas/OCPP16SendDataTransferTriggerMessageProcessorBody";
import OCPP16SendDataTransferV2GCertificateProcessorBody from "./schemas-autogenerated/components/schemas/OCPP16SendDataTransferV2GCertificateProcessorBody";
import OCPP16SendLocalListProcessorBody from "./schemas-autogenerated/components/schemas/OCPP16SendLocalListProcessorBody";
import OCPP16SetChargingProfileProcessorBody from "./schemas-autogenerated/components/schemas/OCPP16SetChargingProfileProcessorBody";
import OCPP16TriggerMessageProcessorBody from "./schemas-autogenerated/components/schemas/OCPP16TriggerMessageProcessorBody";
import OCPP16UnlockConnectorProcessorBody from "./schemas-autogenerated/components/schemas/OCPP16UnlockConnectorProcessorBody";

import OCPP20CancelReservationProcessorBody from "./schemas-autogenerated/components/schemas/OCPP20CancelReservationProcessorBody";
import OCPP20ChangeAvailabilityProcessorBody from "./schemas-autogenerated/components/schemas/OCPP20ChangeAvailabilityProcessorBody";
import OCPP20ClearCacheProcessorBody from "./schemas-autogenerated/components/schemas/OCPP20ClearCacheProcessorBody";
import OCPP20ClearChargingProfileProcessorBody from "./schemas-autogenerated/components/schemas/OCPP20ClearChargingProfileProcessorBody";
import OCPP20GetBaseReportProcessorBody from "./schemas-autogenerated/components/schemas/OCPP20GetBaseReportProcessorBody";
import OCPP20GetLocalListVersionProcessorBody from "./schemas-autogenerated/components/schemas/OCPP20GetLocalListVersionProcessorBody";
import OCPP20GetReportProcessorBody from "./schemas-autogenerated/components/schemas/OCPP20GetReportProcessorBody";
import OCPP20GetVariablesProcessorBody from "./schemas-autogenerated/components/schemas/OCPP20GetVariablesProcessorBody";
import OCPP20RemoteStartTransactionProcessorBody from "./schemas-autogenerated/components/schemas/OCPP20RemoteStartTransactionProcessorBody";
import OCPP20RemoteStopTransactionProcessorBody from "./schemas-autogenerated/components/schemas/OCPP20RemoteStopTransactionProcessorBody";
import OCPP20ReserveNowProcessorBody from "./schemas-autogenerated/components/schemas/OCPP20ReserveNowProcessorBody";
import OCPP20ResetProcessorBody from "./schemas-autogenerated/components/schemas/OCPP20ResetProcessorBody";
import OCPP20SendDataTransferProcessorBody from "./schemas-autogenerated/components/schemas/OCPP20SendDataTransferProcessorBody";
import OCPP20SendLocalListProcessorBody from "./schemas-autogenerated/components/schemas/OCPP20SendLocalListProcessorBody";
import OCPP20SetVariablesProcessorBody from "./schemas-autogenerated/components/schemas/OCPP20SetVariablesProcessorBody";
import OCPP20UnlockConnectorProcessorBody from "./schemas-autogenerated/components/schemas/OCPP20UnlockConnectorProcessorBody";

import ResetType from "./schemas-autogenerated/components/schemas/ResetType";
import ValidationError from "./schemas-autogenerated/components/schemas/ValidationError";

import OCPPV16EnumsUpdateType from "./schemas-autogenerated/components/schemas/ocpp__v16__enums__UpdateType";
import OCPPV201EnumsUpdateType from "./schemas-autogenerated/components/schemas/ocpp__v201__enums__UpdateType";

export default {
  ChargingProfilePurposeType,
  ChargingRateUnitType,
  HTTPValidationError,
  MessageTrigger,

  OCPP16CancelReservationProcessorBody,
  OCPP16ChangeAvailabilityProcessorBody,
  OCPP16ChangeConfigurationAuthenticationProcessorBody,
  OCPP16ChangeConfigurationProcessorBody,
  OCPP16ClearCacheProcessorBody,
  OCPP16ClearChargingProfileProcessorBody,
  OCPP16ExtendedTriggerMessageProcessorBody,
  OCPP16GetCompositeScheduleProcessorBody,
  OCPP16GetConfigurationAuthenticationProcessorBody,
  OCPP16GetConfigurationProcessorBody,
  OCPP16GetDiagnosticsProcessorBody,
  OCPP16GetLocalListVersionProcessorBody,
  OCPP16HeartbeatProcessorBody,
  OCPP16RemoteStartTransactionProcessorBody,
  OCPP16RemoteStopTransactionProcessorBody,
  OCPP16ReserveNowProcessorBody,
  OCPP16ResetProcessorBody,
  OCPP16SendDataTransferCertificateInstallationProcessorBody,
  OCPP16SendDataTransferCertificateSignedProcessorBody,
  OCPP16SendDataTransferGetCertificateStatusProcessorBody,
  OCPP16SendDataTransferGetInstalledCertificateIdsProcessorBody,
  OCPP16SendDataTransferProcessorBody,
  OCPP16SendDataTransferTriggerMessageProcessorBody,
  OCPP16SendDataTransferV2GCertificateProcessorBody,
  OCPP16SendLocalListProcessorBody,
  OCPP16SetChargingProfileProcessorBody,
  OCPP16TriggerMessageProcessorBody,
  OCPP16UnlockConnectorProcessorBody,

  OCPP20CancelReservationProcessorBody,
  OCPP20ChangeAvailabilityProcessorBody,
  OCPP20ClearCacheProcessorBody,
  OCPP20ClearChargingProfileProcessorBody,
  OCPP20GetBaseReportProcessorBody,
  OCPP20GetLocalListVersionProcessorBody,
  OCPP20GetReportProcessorBody,
  OCPP20GetVariablesProcessorBody,
  OCPP20RemoteStartTransactionProcessorBody,
  OCPP20RemoteStopTransactionProcessorBody,
  OCPP20ReserveNowProcessorBody,
  OCPP20ResetProcessorBody,
  OCPP20SendDataTransferProcessorBody,
  OCPP20SendLocalListProcessorBody,
  OCPP20SetVariablesProcessorBody,
  OCPP20UnlockConnectorProcessorBody,

  ResetType,
  ValidationError,

  OCPPV16EnumsUpdateType,
  OCPPV201EnumsUpdateType,
};
