import Accessibility from "./schemas-autogenerated/components/schemas/Accessibility";
import AddressIso19773 from "./schemas-autogenerated/components/schemas/AddressIso19773";
import AuthenticationMode from "./schemas-autogenerated/components/schemas/AuthenticationMode";
import ChargingFacility from "./schemas-autogenerated/components/schemas/ChargingFacility";
import ChargingNotificationType from "./schemas-autogenerated/components/schemas/ChargingNotificationType";
import ERoamingAcknowledgment from "./schemas-autogenerated/components/schemas/ERoamingAcknowledgment";
import ERoamingAuthorizationStart from "./schemas-autogenerated/components/schemas/ERoamingAuthorizationStart";
import ERoamingAuthorizationStartAuthorizationStopIdentificationsInner from "./schemas-autogenerated/components/schemas/ERoamingAuthorizationStartAuthorizationStopIdentificationsInner";
import ERoamingAuthorizationStop from "./schemas-autogenerated/components/schemas/ERoamingAuthorizationStop";
import ERoamingAuthorizeRemoteReservationStart from "./schemas-autogenerated/components/schemas/ERoamingAuthorizeRemoteReservationStart";
import ERoamingAuthorizeRemoteReservationStop from "./schemas-autogenerated/components/schemas/ERoamingAuthorizeRemoteReservationStop";
import ERoamingAuthorizeRemoteStart from "./schemas-autogenerated/components/schemas/ERoamingAuthorizeRemoteStart";
import ERoamingAuthorizeRemoteStop from "./schemas-autogenerated/components/schemas/ERoamingAuthorizeRemoteStop";
import ERoamingAuthorizeStart from "./schemas-autogenerated/components/schemas/ERoamingAuthorizeStart";
import ERoamingAuthorizeStop from "./schemas-autogenerated/components/schemas/ERoamingAuthorizeStop";
import ERoamingChargeDetailRecord from "./schemas-autogenerated/components/schemas/ERoamingChargeDetailRecord";
import ERoamingChargeDetailRecordCalibrationLawVerificationInfo from "./schemas-autogenerated/components/schemas/ERoamingChargeDetailRecordCalibrationLawVerificationInfo";
import ERoamingChargeDetailRecordMeterValueInBetween from "./schemas-autogenerated/components/schemas/ERoamingChargeDetailRecordMeterValueInBetween";
import ERoamingChargeDetailRecordSignedMeteringValuesInner from "./schemas-autogenerated/components/schemas/ERoamingChargeDetailRecordSignedMeteringValuesInner";
import ERoamingChargingNotificationEnd from "./schemas-autogenerated/components/schemas/ERoamingChargingNotificationEnd";
import ERoamingChargingNotificationError from "./schemas-autogenerated/components/schemas/ERoamingChargingNotificationError";
import ERoamingChargingNotificationProgress from "./schemas-autogenerated/components/schemas/ERoamingChargingNotificationProgress";
import ERoamingChargingNotificationStart from "./schemas-autogenerated/components/schemas/ERoamingChargingNotificationStart";
import ERoamingPushEVSEPricing from "./schemas-autogenerated/components/schemas/ERoamingPushEVSEPricing";
import ERoamingPushEVSEPricingEVSEPricingInner from "./schemas-autogenerated/components/schemas/ERoamingPushEVSEPricingEVSEPricingInner";
import ERoamingPushEvseData from "./schemas-autogenerated/components/schemas/ERoamingPushEvseData";
import ERoamingPushEvseDataOperatorEvseData from "./schemas-autogenerated/components/schemas/ERoamingPushEvseDataOperatorEvseData";
import ERoamingPushEvseStatus from "./schemas-autogenerated/components/schemas/ERoamingPushEvseStatus";
import ERoamingPushEvseStatusOperatorEvseStatus from "./schemas-autogenerated/components/schemas/ERoamingPushEvseStatusOperatorEvseStatus";
import ERoamingPushEvseStatusOperatorEvseStatusEvseStatusRecordInner from "./schemas-autogenerated/components/schemas/ERoamingPushEvseStatusOperatorEvseStatusEvseStatusRecordInner";
import ERoamingPushPricingProductData from "./schemas-autogenerated/components/schemas/ERoamingPushPricingProductData";
import ERoamingPushPricingProductDataPricingProductData from "./schemas-autogenerated/components/schemas/ERoamingPushPricingProductDataPricingProductData";
import EnergySource from "./schemas-autogenerated/components/schemas/EnergySource";
import EvseDataRecord from "./schemas-autogenerated/components/schemas/EvseDataRecord";
import GeoCoordinates from "./schemas-autogenerated/components/schemas/GeoCoordinates";
import GeoCoordinatesDecimalDegree from "./schemas-autogenerated/components/schemas/GeoCoordinatesDecimalDegree";
import GeoCoordinatesDegreeMinuteSeconds from "./schemas-autogenerated/components/schemas/GeoCoordinatesDegreeMinuteSeconds";
import GeoCoordinatesGoogle from "./schemas-autogenerated/components/schemas/GeoCoordinatesGoogle";
import HTTPValidationError from "./schemas-autogenerated/components/schemas/HTTPValidationError";
import Identification from "./schemas-autogenerated/components/schemas/Identification";
import InfoTextType from "./schemas-autogenerated/components/schemas/InfoTextType";
import OpeningTimes from "./schemas-autogenerated/components/schemas/OpeningTimes";
import OpeningTimesPeriodInner from "./schemas-autogenerated/components/schemas/OpeningTimesPeriodInner";
import PaymentOption from "./schemas-autogenerated/components/schemas/PaymentOption";
import Plug from "./schemas-autogenerated/components/schemas/Plug";
import PlugAndChargeIdentification from "./schemas-autogenerated/components/schemas/PlugAndChargeIdentification";
import PricingProductDataRecord from "./schemas-autogenerated/components/schemas/PricingProductDataRecord";
import PricingProductDataRecordAdditionalReferencesInner from "./schemas-autogenerated/components/schemas/PricingProductDataRecordAdditionalReferencesInner";
import PricingProductDataRecordProductAvailabilityTimesInner from "./schemas-autogenerated/components/schemas/PricingProductDataRecordProductAvailabilityTimesInner";
import PricingProductDataRecordProductAvailabilityTimesInnerPeriodsInner from "./schemas-autogenerated/components/schemas/PricingProductDataRecordProductAvailabilityTimesInnerPeriodsInner";
import PullEvseDataRecordEnvironmentalImpact from "./schemas-autogenerated/components/schemas/PullEvseDataRecordEnvironmentalImpact";
import QRCodeIdentificationInput from "./schemas-autogenerated/components/schemas/QRCodeIdentification-Input";
import QRCodeIdentificationOutput from "./schemas-autogenerated/components/schemas/QRCodeIdentification-Output";
import QRCodeIdentificationHashedPIN from "./schemas-autogenerated/components/schemas/QRCodeIdentificationHashedPIN";
import QRCodeIdentificationHashedPINLegacyHashData from "./schemas-autogenerated/components/schemas/QRCodeIdentificationHashedPINLegacyHashData";
import RFIDIdentification from "./schemas-autogenerated/components/schemas/RFIDIdentification";
import RFIDMifareFamilyIdentification from "./schemas-autogenerated/components/schemas/RFIDMifareFamilyIdentification";
import RemoteIdentification from "./schemas-autogenerated/components/schemas/RemoteIdentification";
import StatusCode from "./schemas-autogenerated/components/schemas/StatusCode";
import ValidationError from "./schemas-autogenerated/components/schemas/ValidationError";
import ValueAddedService from "./schemas-autogenerated/components/schemas/ValueAddedService";

export default {
  Accessibility,
  AddressIso19773,
  AuthenticationMode,
  ChargingFacility,
  ChargingNotificationType,
  ERoamingAcknowledgment,
  ERoamingAuthorizationStart,
  ERoamingAuthorizationStartAuthorizationStopIdentificationsInner,
  ERoamingAuthorizationStop,
  ERoamingAuthorizeRemoteReservationStart,
  ERoamingAuthorizeRemoteReservationStop,
  ERoamingAuthorizeRemoteStart,
  ERoamingAuthorizeRemoteStop,
  ERoamingAuthorizeStart,
  ERoamingAuthorizeStop,
  ERoamingChargeDetailRecord,
  ERoamingChargeDetailRecordCalibrationLawVerificationInfo,
  ERoamingChargeDetailRecordMeterValueInBetween,
  ERoamingChargeDetailRecordSignedMeteringValuesInner,
  ERoamingChargingNotificationEnd,
  ERoamingChargingNotificationError,
  ERoamingChargingNotificationProgress,
  ERoamingChargingNotificationStart,
  ERoamingPushEVSEPricing,
  ERoamingPushEVSEPricingEVSEPricingInner,
  ERoamingPushEvseData,
  ERoamingPushEvseDataOperatorEvseData,
  ERoamingPushEvseStatus,
  ERoamingPushEvseStatusOperatorEvseStatus,
  ERoamingPushEvseStatusOperatorEvseStatusEvseStatusRecordInner,
  ERoamingPushPricingProductData,
  ERoamingPushPricingProductDataPricingProductData,
  EnergySource,
  EvseDataRecord,
  GeoCoordinates,
  GeoCoordinatesDecimalDegree,
  GeoCoordinatesDegreeMinuteSeconds,
  GeoCoordinatesGoogle,
  HTTPValidationError,
  Identification,
  InfoTextType,
  OpeningTimes,
  OpeningTimesPeriodInner,
  PaymentOption,
  Plug,
  PlugAndChargeIdentification,
  PricingProductDataRecord,
  PricingProductDataRecordAdditionalReferencesInner,
  PricingProductDataRecordProductAvailabilityTimesInner,
  PricingProductDataRecordProductAvailabilityTimesInnerPeriodsInner,
  PullEvseDataRecordEnvironmentalImpact,
  QRCodeIdentificationInput,
  QRCodeIdentificationOutput,
  QRCodeIdentificationHashedPIN,
  QRCodeIdentificationHashedPINLegacyHashData,
  RFIDIdentification,
  RFIDMifareFamilyIdentification,
  RemoteIdentification,
  StatusCode,
  ValidationError,
  ValueAddedService,
};
