import Authorize from "./schemas-autogenerated/paths/_authorize";
import ConnectorStateId from "./schemas-autogenerated/paths/_connector_state_{id}";
import Context from "./schemas-autogenerated/paths/_context";
import StartCharging from "./schemas-autogenerated/paths/_startcharging";
import StartChargingIso15118 from "./schemas-autogenerated/paths/_startchargingiso15118";
import Unplug from "./schemas-autogenerated/paths/_unplug";
import UpdateContext from "./schemas-autogenerated/paths/_update-context";

export default {
  Authorize,
  ConnectorStateId,
  Context,
  StartCharging,
  StartChargingIso15118,
  Unplug,
  UpdateContext,
};
