import Accessibility from "./schemas-autogenerated/components/schemas/Accessibility";
import AddressIso19773 from "./schemas-autogenerated/components/schemas/AddressIso19773";
import AuthenticationMode from "./schemas-autogenerated/components/schemas/AuthenticationMode";
import ChargingFacility from "./schemas-autogenerated/components/schemas/ChargingFacility";
import ChargingNotificationType from "./schemas-autogenerated/components/schemas/ChargingNotificationType";
import ChargingPoolID from "./schemas-autogenerated/components/schemas/ChargingPoolID";
import CountryCode from "./schemas-autogenerated/components/schemas/CountryCode";
import CurrencyID from "./schemas-autogenerated/components/schemas/CurrencyID";
import EnergySource from "./schemas-autogenerated/components/schemas/EnergySource";
import EvcoID from "./schemas-autogenerated/components/schemas/EvcoID";
import EvseDataRecord from "./schemas-autogenerated/components/schemas/EvseDataRecord";
import EvseID from "./schemas-autogenerated/components/schemas/EvseID";
import EvseStatus from "./schemas-autogenerated/components/schemas/EvseStatus";
import GeoCoordinates from "./schemas-autogenerated/components/schemas/GeoCoordinates";
import GeoCoordinatesResponseFormat from "./schemas-autogenerated/components/schemas/GeoCoordinatesResponseFormat";
import Identification from "./schemas-autogenerated/components/schemas/Identification";
import InfoTextType from "./schemas-autogenerated/components/schemas/InfoTextType";
import OpeningTimes from "./schemas-autogenerated/components/schemas/OpeningTimes";
import OperatorID from "./schemas-autogenerated/components/schemas/OperatorID";
import PaymentOption from "./schemas-autogenerated/components/schemas/PaymentOption";
import Plug from "./schemas-autogenerated/components/schemas/Plug";
import PlugAndChargeIdentification from "./schemas-autogenerated/components/schemas/PlugAndChargeIdentification";
import PricingProductDataRecord from "./schemas-autogenerated/components/schemas/PricingProductDataRecord";
import ProductID from "./schemas-autogenerated/components/schemas/ProductID";
import ProviderAuthenticationData from "./schemas-autogenerated/components/schemas/ProviderAuthenticationData";
import ProviderID from "./schemas-autogenerated/components/schemas/ProviderID";
import ProviderIDAsterisk from "./schemas-autogenerated/components/schemas/ProviderIDAsterisk";
import PullEvseDataRecord from "./schemas-autogenerated/components/schemas/PullEvseDataRecord";
import QRCodeIdentification from "./schemas-autogenerated/components/schemas/QRCodeIdentification";
import RFIDIdentification from "./schemas-autogenerated/components/schemas/RFIDIdentification";
import RFIDMifareFamilyIdentification from "./schemas-autogenerated/components/schemas/RFIDMifareFamilyIdentification";
import ReferenceUnit from "./schemas-autogenerated/components/schemas/ReferenceUnit";
import RemoteIdentification from "./schemas-autogenerated/components/schemas/RemoteIdentification";
import SessionID from "./schemas-autogenerated/components/schemas/SessionID";
import StatusCode from "./schemas-autogenerated/components/schemas/StatusCode";
import UID from "./schemas-autogenerated/components/schemas/UID";
import ValueAddedService from "./schemas-autogenerated/components/schemas/ValueAddedService";
import eRoamingAcknowledgment from "./schemas-autogenerated/components/schemas/eRoamingAcknowledgment";
import eRoamingAuthorizationStart from "./schemas-autogenerated/components/schemas/eRoamingAuthorizationStart";
import eRoamingAuthorizationStop from "./schemas-autogenerated/components/schemas/eRoamingAuthorizationStop";
import eRoamingAuthorizeRemoteReservationStart from "./schemas-autogenerated/components/schemas/eRoamingAuthorizeRemoteReservationStart";
import eRoamingAuthorizeRemoteReservationStop from "./schemas-autogenerated/components/schemas/eRoamingAuthorizeRemoteReservationStop";
import eRoamingAuthorizeRemoteStart from "./schemas-autogenerated/components/schemas/eRoamingAuthorizeRemoteStart";
import eRoamingAuthorizeRemoteStop from "./schemas-autogenerated/components/schemas/eRoamingAuthorizeRemoteStop";
import eRoamingAuthorizeStart from "./schemas-autogenerated/components/schemas/eRoamingAuthorizeStart";
import eRoamingAuthorizeStop from "./schemas-autogenerated/components/schemas/eRoamingAuthorizeStop";
import eRoamingChargeDetailRecord from "./schemas-autogenerated/components/schemas/eRoamingChargeDetailRecord";
import eRoamingChargeDetailRecords from "./schemas-autogenerated/components/schemas/eRoamingChargeDetailRecords";
import eRoamingChargingNotificationEnd from "./schemas-autogenerated/components/schemas/eRoamingChargingNotificationEnd";
import eRoamingChargingNotificationError from "./schemas-autogenerated/components/schemas/eRoamingChargingNotificationError";
import eRoamingChargingNotificationProgress from "./schemas-autogenerated/components/schemas/eRoamingChargingNotificationProgress";
import eRoamingChargingNotificationStart from "./schemas-autogenerated/components/schemas/eRoamingChargingNotificationStart";
import eRoamingEVSEData from "./schemas-autogenerated/components/schemas/eRoamingEVSEData";
import eRoamingEVSEPricing from "./schemas-autogenerated/components/schemas/eRoamingEVSEPricing";
import eRoamingEVSEStatus from "./schemas-autogenerated/components/schemas/eRoamingEVSEStatus";
import eRoamingEVSEStatusByID from "./schemas-autogenerated/components/schemas/eRoamingEVSEStatusByID";
import eRoamingGetChargeDetailRecords from "./schemas-autogenerated/components/schemas/eRoamingGetChargeDetailRecords";
import eRoamingPricingProductData from "./schemas-autogenerated/components/schemas/eRoamingPricingProductData";
import eRoamingPullEVSEData from "./schemas-autogenerated/components/schemas/eRoamingPullEVSEData";
import eRoamingPullEVSEPricing from "./schemas-autogenerated/components/schemas/eRoamingPullEVSEPricing";
import eRoamingPullEVSEStatus from "./schemas-autogenerated/components/schemas/eRoamingPullEVSEStatus";
import eRoamingPullEVSEStatusByID from "./schemas-autogenerated/components/schemas/eRoamingPullEVSEStatusByID";
import eRoamingPullEVSEStatusByOperatorID from "./schemas-autogenerated/components/schemas/eRoamingPullEVSEStatusByOperatorID";
import eRoamingPullPricingProductData from "./schemas-autogenerated/components/schemas/eRoamingPullPricingProductData";
import eRoamingPushAuthenticationData from "./schemas-autogenerated/components/schemas/eRoamingPushAuthenticationData";

export default {
  Accessibility,
  AddressIso19773,
  AuthenticationMode,
  ChargingFacility,
  ChargingNotificationType,
  ChargingPoolID,
  CountryCode,
  CurrencyID,
  EnergySource,
  EvcoID,
  EvseDataRecord,
  EvseID,
  EvseStatus,
  GeoCoordinates,
  GeoCoordinatesResponseFormat,
  Identification,
  InfoTextType,
  OpeningTimes,
  OperatorID,
  PaymentOption,
  Plug,
  PlugAndChargeIdentification,
  PricingProductDataRecord,
  ProductID,
  ProviderAuthenticationData,
  ProviderID,
  ProviderIDAsterisk,
  PullEvseDataRecord,
  QRCodeIdentification,
  RFIDIdentification,
  RFIDMifareFamilyIdentification,
  ReferenceUnit,
  RemoteIdentification,
  SessionID,
  StatusCode,
  UID,
  ValueAddedService,
  eRoamingAcknowledgment,
  eRoamingAuthorizationStart,
  eRoamingAuthorizationStop,
  eRoamingAuthorizeRemoteReservationStart,
  eRoamingAuthorizeRemoteReservationStop,
  eRoamingAuthorizeRemoteStart,
  eRoamingAuthorizeRemoteStop,
  eRoamingAuthorizeStart,
  eRoamingAuthorizeStop,
  eRoamingChargeDetailRecord,
  eRoamingChargeDetailRecords,
  eRoamingChargingNotificationEnd,
  eRoamingChargingNotificationError,
  eRoamingChargingNotificationProgress,
  eRoamingChargingNotificationStart,
  eRoamingEVSEData,
  eRoamingEVSEPricing,
  eRoamingEVSEStatus,
  eRoamingEVSEStatusByID,
  eRoamingGetChargeDetailRecords,
  eRoamingPricingProductData,
  eRoamingPullEVSEData,
  eRoamingPullEVSEPricing,
  eRoamingPullEVSEStatus,
  eRoamingPullEVSEStatusByID,
  eRoamingPullEVSEStatusByOperatorID,
  eRoamingPullPricingProductData,
  eRoamingPushAuthenticationData,
};
